---@see SWOutfitTypeEnum
---@see SWCreatureTypeEnum

-- Do we really want to include passengers in the producible/consumable code?
-- LocationSystem
-- 	.addProducible(
-- 		ProducibleConfig.new("worker", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("outfit", 1)
-- 	)
-- 	.addProducible(
-- 		ProducibleConfig.new("fisher", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("outfit", 2)
-- 	)
-- 	.addProducible(
-- 		ProducibleConfig.new("waiter", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("outfit", 3)
-- 	)
-- 	.addProducible(
-- 		ProducibleConfig.new("swimsuit", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("outfit", 4)
-- 	)
-- 	.addProducible(
-- 		ProducibleConfig.new("military", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("outfit", 5)
-- 	)
-- 	.addProducible(
-- 		ProducibleConfig.new("office", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("outfit", 6)
-- 	)
-- 	.addProducible(
-- 		ProducibleConfig.new("police", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("outfit", 7)
-- 	)
-- 	.addProducible(
-- 		ProducibleConfig.new("science", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("outfit", 8)
-- 	)
-- 	.addProducible(
-- 		ProducibleConfig.new("medical", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("outfit", 9)
-- 	)
-- 	.addProducible(
-- 		ProducibleConfig.new("wetsuit", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("outfit", 10)
-- 	)
-- 	.addProducible(
-- 		ProducibleConfig.new("civilian", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("outfit", 11)
-- 	)
-- 	.addProducible(
-- 		ProducibleConfig.new("dog", PRODUCIBLE_TYPES.passenger)
-- 			:addPassengerVariant("creature", 18)
-- 			:addPassengerVariant("creature", 19)
-- 			:addPassengerVariant("creature", 20)
-- 			:addPassengerVariant("creature", 21)
-- 			:addPassengerVariant("creature", 22)
-- 			:addPassengerVariant("creature", 23)
-- 			:addPassengerVariant("creature", 24)
-- 			:addPassengerVariant("creature", 25)
-- 			:addPassengerVariant("creature", 26)
-- 			:addPassengerVariant("creature", 27)
-- 			:addPassengerVariant("creature", 28)
-- 			:addPassengerVariant("creature", 29)
-- 			:addPassengerVariant("creature", 30)
-- 			:addPassengerVariant("creature", 31)
-- 			:addPassengerVariant("creature", 32)
-- 			:addPassengerVariant("creature", 33)
-- 			:addPassengerVariant("creature", 34)
-- 			:addPassengerVariant("creature", 35)
-- 	)
